name: Hexo deploy

on: 
  push:
    paths-ignore:
      - 'source/_GoNotes/**'
      - 'source/_JavaNotes/**'
      - 'source/_PythonNotes/**'
      - 'source/_drafts/**'
      - '.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
        
    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
        
    # Deploy hexo blog website.
    - name: Deploy
      id: deploy
      uses: sma11black/hexo-action@v1.0.3
      with:
        deploy_key: ${{ secrets.HEXO_DEPLOY_KEY }}
        user_name: zhengcurry
        user_email: AYI0000AYI@163.com
        commit_msg: ${{ github.event.head_commit.message }}ion)
    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"
  #sync:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Sync to Gitee
  #      uses: wearerequired/git-mirror-action@master
  #      env:
  #        SSH_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
  #      with:
  #        # 源仓库
  #        source-repo: git@github.com:hiyongz/hiyongz.github.io.git
  #        # 目标仓库
  #        destination-repo: git@gitee.com:hiyong/hiyong.git
  #reload-pages:
  #  needs: sync
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Build Gitee Pages
  #      uses: yanglbme/gitee-pages-action@main
  #      with:
  #        gitee-username: hiyong
  #        gitee-password: ${{ secrets.GITEE_PASSWORD }}
  #        gitee-repo: hiyong/hiyong
  #        branch: master